const fs = require("fs");
const os = require("os");
const path = require("path");
const readline = require("readline");

const OPENAI_ENV_FILE = path.join(os.homedir(), ".openai-env");
const DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1";
const DEFAULT_OPENAI_MODEL = "gpt-4.1-mini";
const DEFAULT_OPENAI_API_FORMAT = "chat_completions";
const DEFAULT_PROXY_URL = "http://127.0.0.1:7890";

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl, prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(String(answer || "").trim()));
  });
}

function isValidApiKey(key) {
  return typeof key === "string" && /^sk-/.test(key) && key.length >= 20;
}

async function askYesNo(rl, prompt, defaultChoice) {
  while (true) {
    const answer = (await ask(rl, prompt)) || defaultChoice;
    const normalized = answer.toLowerCase();
    if (["y", "yes"].includes(normalized)) {
      return true;
    }
    if (["n", "no"].includes(normalized)) {
      return false;
    }
    console.log("Please enter y or n.");
  }
}

async function promptForApiKey(rl) {
  while (true) {
    console.log("Paste your OpenAI API key and press Enter.");
    console.log("Enter q to cancel setup.");
    const apiKey = await ask(rl, "API key: ");
    if (["q", "Q"].includes(apiKey)) {
      throw new Error("Setup cancelled.");
    }
    if (isValidApiKey(apiKey)) {
      return apiKey;
    }
    console.log("Invalid API key format. It should start with 'sk-'.");
  }
}

async function chooseModel(rl) {
  while (true) {
    console.log("\nChoose a default model:");
    console.log("  1) gpt-4.1-mini  - fast and low-cost, good default for agents");
    console.log("  2) gpt-4.1       - stronger general reasoning");
    console.log("  3) Custom model  - enter a model name manually");

    const choice = (await ask(rl, "Model choice [1]: ")) || "1";
    if (choice === "1") {
      return "gpt-4.1-mini";
    }
    if (choice === "2") {
      return "gpt-4.1";
    }
    if (choice === "3") {
      return (await ask(rl, `Enter model name [${DEFAULT_OPENAI_MODEL}]: `)) || DEFAULT_OPENAI_MODEL;
    }
    console.log("Please enter 1, 2, or 3.");
  }
}

function formatEnvFile(config) {
  const lines = [
    "# Generated by setup_openai.js",
    `OPENAI_API_KEY=${JSON.stringify(config.apiKey)}`,
    `OPENAI_BASE_URL=${JSON.stringify(config.baseUrl)}`,
    `OPENAI_MODEL=${JSON.stringify(config.model)}`,
    `OPENAI_API_FORMAT=${JSON.stringify(config.apiFormat)}`,
  ];

  if (config.proxyUrl) {
    lines.push(`HTTP_PROXY=${JSON.stringify(config.proxyUrl)}`);
    lines.push(`HTTPS_PROXY=${JSON.stringify(config.proxyUrl)}`);
  }

  return `${lines.join("\n")}\n`;
}

async function writeEnvFile(config) {
  await fs.promises.mkdir(path.dirname(OPENAI_ENV_FILE), { recursive: true });
  await fs.promises.writeFile(OPENAI_ENV_FILE, formatEnvFile(config), "utf8");
}

function printNextSteps(config) {
  console.log("\nSetup complete.");
  console.log(`Saved OpenAI config to ${OPENAI_ENV_FILE}`);
  console.log("Mochi reads this file directly at runtime, so restarting the Extension Development Host is enough.");

  if (process.platform === "win32") {
    console.log("Optional for the current PowerShell session:");
    console.log("  $env:OPENAI_BASE_URL=\"https://api.openai.com/v1\"");
    console.log(`  $env:OPENAI_MODEL=\"${config.model}\"`);
    console.log("  $env:OPENAI_API_FORMAT=\"chat_completions\"");
    if (config.proxyUrl) {
      console.log(`  $env:HTTP_PROXY=\"${config.proxyUrl}\"`);
      console.log(`  $env:HTTPS_PROXY=\"${config.proxyUrl}\"`);
    }
  } else {
    console.log("Optional for the current shell session:");
    console.log(`  source ${OPENAI_ENV_FILE}`);
  }

  console.log("\nNext steps:");
  console.log("1) Run npm install if you have not installed dependencies yet.");
  console.log("2) Press F5 in VS Code and choose 'Run Local Agent Extension'.");
  console.log("3) In the Extension Development Host window, run 'Local Agent: Open Chat'.");
}

async function main() {
  const rl = createInterface();
  try {
    console.log("OpenAI setup script");
    console.log(`Using config file: ${OPENAI_ENV_FILE}`);
    console.log("This script works on Windows, macOS, and Linux.");
    console.log("If you need an API key, open: https://platform.openai.com/api-keys");

    let apiKey = process.env.OPENAI_API_KEY || "";
    if (apiKey && isValidApiKey(apiKey)) {
      const reuse = await askYesNo(
        rl,
        "Detected OPENAI_API_KEY in the current environment. Reuse it? [y/n, default y]: ",
        "y"
      );
      if (!reuse) {
        apiKey = await promptForApiKey(rl);
      }
    } else {
      apiKey = await promptForApiKey(rl);
    }

    const model = await chooseModel(rl);
    const useProxy = await askYesNo(rl, "Configure HTTP/HTTPS proxy? [y/n, default n]: ", "n");
    const proxyUrl = useProxy
      ? (await ask(rl, `Proxy URL [${DEFAULT_PROXY_URL}]: `)) || DEFAULT_PROXY_URL
      : "";

    const config = {
      apiKey,
      baseUrl: DEFAULT_OPENAI_BASE_URL,
      model,
      apiFormat: DEFAULT_OPENAI_API_FORMAT,
      proxyUrl,
    };

    await writeEnvFile(config);
    printNextSteps(config);
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error(error.message || String(error));
  process.exitCode = 1;
});