const fs = require("fs");
const os = require("os");
const path = require("path");
const readline = require("readline");
const { loadOpenAIEnvFile } = require("../src/runtime/support/openai_env");

const OPENAI_ENV_FILE = path.join(os.homedir(), ".openai-env");
const DEFAULT_OPENAI_BASE_URL = "https://api.openai.com/v1";
const DEFAULT_OPENAI_MODEL = "gpt-4.1-mini";
const DEFAULT_OPENAI_API_FORMAT = "chat_completions";
const DEFAULT_GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai";
const DEFAULT_GEMINI_MODEL = "gemini-2.5-flash";
const DEFAULT_PROXY_URL = "http://127.0.0.1:7890";

function createInterface() {
  return readline.createInterface({ 
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl, prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(String(answer || "").trim()));
  });
}

function isValidApiKey(key) {
  return typeof key === "string" && /^sk-/.test(key) && key.length >= 20;
}

function isValidGeminiApiKey(key) {
  return typeof key === "string" && /^AIza/.test(key) && key.length >= 20;
}

function isValidApiKeyForProvider(provider, key) {
  return provider === "gemini" ? isValidGeminiApiKey(key) : isValidApiKey(key);
}

function hasEnvKey(key) {
  return Object.prototype.hasOwnProperty.call(process.env, key);
}

async function askYesNo(rl, prompt, defaultChoice) {
  while (true) {
    const answer = (await ask(rl, prompt)) || defaultChoice;
    const normalized = answer.toLowerCase();
    if (["y", "yes"].includes(normalized)) {
      return true;
    }
    if (["n", "no"].includes(normalized)) {
      return false;
    }
    console.log("Please enter y or n.");
  }
}

async function chooseProvider(rl) {
  while (true) {
    console.log("\nChoose a model provider:");
    console.log("  1) OpenAI  - api.openai.com with an sk- API key");
    console.log("  2) Gemini  - Google AI Studio through an OpenAI-compatible endpoint");

    const choice = (await ask(rl, "Provider choice [1]: ")) || "1";
    if (choice === "1") {
      return "openai";
    }
    if (choice === "2") {
      return "gemini";
    }
    console.log("Please enter 1 or 2.");
  }
}

async function promptForApiKey(rl, provider) {
  const label = provider === "gemini" ? "Gemini" : "OpenAI";
  const format = provider === "gemini" ? "AIza..." : "sk-...";
  const keyUrl =
    provider === "gemini"
      ? "https://aistudio.google.com/app/apikey"
      : "https://platform.openai.com/api-keys";

  while (true) {
    console.log(`Paste your ${label} API key and press Enter.`);
    console.log(`Expected format: ${format}`);
    console.log(`Keys: ${keyUrl}`);
    console.log("Enter q to cancel setup.");
    const apiKey = await ask(rl, "API key: ");
    if (["q", "Q"].includes(apiKey)) {
      throw new Error("Setup cancelled.");
    }
    if (isValidApiKeyForProvider(provider, apiKey)) {
      return apiKey;
    }
    console.log(`Invalid ${label} API key format.`);
  }
}

async function chooseModel(rl, provider) {
  if (provider === "gemini") {
    while (true) {
      console.log("\nChoose a default model:");
      console.log("  1) gemini-2.5-flash  - recommended for local agent development");
      console.log("  2) gemini-2.5-pro    - stronger, higher quota pressure");
      console.log("  3) Custom model      - enter a model name manually");

      const choice = (await ask(rl, "Model choice [1]: ")) || "1";
      if (choice === "1") {
        return "gemini-2.5-flash";
      }
      if (choice === "2") {
        return "gemini-2.5-pro";
      }
      if (choice === "3") {
        return (await ask(rl, `Enter model name [${DEFAULT_GEMINI_MODEL}]: `)) || DEFAULT_GEMINI_MODEL;
      }
      console.log("Please enter 1, 2, or 3.");
    }
  }

  while (true) {
    console.log("\nChoose a default model:");
    console.log("  1) gpt-4.1-mini  - fast and low-cost, good default for agents");
    console.log("  2) gpt-4.1       - stronger general reasoning");
    console.log("  3) Custom model  - enter a model name manually");

    const choice = (await ask(rl, "Model choice [1]: ")) || "1";
    if (choice === "1") {
      return "gpt-4.1-mini";
    }
    if (choice === "2") {
      return "gpt-4.1";
    }
    if (choice === "3") {
      return (await ask(rl, `Enter model name [${DEFAULT_OPENAI_MODEL}]: `)) || DEFAULT_OPENAI_MODEL;
    }
    console.log("Please enter 1, 2, or 3.");
  }
}

function formatEnvFile(config) {
  const lines = [
    "# Generated by setup_model.js",
    `MOCHI_MODEL_PROVIDER=${JSON.stringify(config.provider)}`,
    `OPENAI_API_KEY=${JSON.stringify(config.apiKey)}`,
    `OPENAI_BASE_URL=${JSON.stringify(config.baseUrl)}`,
    `OPENAI_MODEL=${JSON.stringify(config.model)}`,
    `OPENAI_API_FORMAT=${JSON.stringify(config.apiFormat)}`,
  ];

  if (config.openaiApiKey) {
    lines.push(`MOCHI_OPENAI_API_KEY=${JSON.stringify(config.openaiApiKey)}`);
  }

  if (config.geminiApiKey) {
    lines.push(`GEMINI_API_KEY=${JSON.stringify(config.geminiApiKey)}`);
  }

  if (config.proxyUrl) {
    lines.push(`HTTP_PROXY=${JSON.stringify(config.proxyUrl)}`);
    lines.push(`HTTPS_PROXY=${JSON.stringify(config.proxyUrl)}`);
  }

  return `${lines.join("\n")}\n`;
}

async function writeEnvFile(config) {
  await fs.promises.mkdir(path.dirname(OPENAI_ENV_FILE), { recursive: true });
  await fs.promises.writeFile(OPENAI_ENV_FILE, formatEnvFile(config), "utf8");
}

function printNextSteps(config) {
  console.log("\nSetup complete.");
  console.log(`Saved ${config.provider} model config to ${OPENAI_ENV_FILE}`);
  console.log("Mochi reads this file directly at runtime, so restarting the Extension Development Host is enough.");

  if (process.platform === "win32") {
    console.log("Optional for the current PowerShell session:");
    console.log(`  $env:MOCHI_MODEL_PROVIDER=\"${config.provider}\"`);
    console.log(`  $env:OPENAI_BASE_URL=\"${config.baseUrl}\"`);
    console.log(`  $env:OPENAI_MODEL=\"${config.model}\"`);
    console.log(`  $env:OPENAI_API_FORMAT=\"${config.apiFormat}\"`);
    if (config.proxyUrl) {
      console.log(`  $env:HTTP_PROXY=\"${config.proxyUrl}\"`);
      console.log(`  $env:HTTPS_PROXY=\"${config.proxyUrl}\"`);
    }
  } else {
    console.log("Optional for the current shell session:");
    console.log(`  source ${OPENAI_ENV_FILE}`);
  }

  console.log("\nNext steps:");
  console.log("1) Run npm install if you have not installed dependencies yet.");
  console.log("2) Press F5 in VS Code and choose 'Run Local Agent Extension'.");
  console.log("3) In the Extension Development Host window, run 'Local Agent: Open Chat'.");
}

async function main() {
  const rl = createInterface();
  try {
    console.log("Mochi model setup script");
    console.log(`Using config file: ${OPENAI_ENV_FILE}`);
    console.log("This script works on Windows, macOS, and Linux.");
    console.log("For normal VS Code usage, prefer the 'Mochi: Configure Model Credentials' command.");

    loadOpenAIEnvFile({ override: false });

    const provider = await chooseProvider(rl);
    const providerEnvKey = provider === "gemini" ? "GEMINI_API_KEY" : "MOCHI_OPENAI_API_KEY";
    let apiKey = process.env[providerEnvKey] || process.env.OPENAI_API_KEY || "";
    if (apiKey && isValidApiKeyForProvider(provider, apiKey)) {
      const reuse = await askYesNo(
        rl,
        `Detected ${hasEnvKey(providerEnvKey) ? providerEnvKey : "OPENAI_API_KEY"} in the current environment. Reuse it? [y/n, default y]: `,
        "y"
      );
      if (!reuse) {
        apiKey = await promptForApiKey(rl, provider);
      }
    } else {
      apiKey = await promptForApiKey(rl, provider);
    }

    const model = await chooseModel(rl, provider);
    const useProxy = await askYesNo(rl, "Configure HTTP/HTTPS proxy? [y/n, default n]: ", "n");
    const proxyUrl = useProxy
      ? (await ask(rl, `Proxy URL [${DEFAULT_PROXY_URL}]: `)) || DEFAULT_PROXY_URL
      : "";

    const config = {
      provider,
      apiKey,
      openaiApiKey:
        provider === "openai"
          ? apiKey
          : process.env.MOCHI_OPENAI_API_KEY || (isValidApiKey(process.env.OPENAI_API_KEY) ? process.env.OPENAI_API_KEY : ""),
      geminiApiKey:
        provider === "gemini"
          ? apiKey
          : process.env.GEMINI_API_KEY || (isValidGeminiApiKey(process.env.OPENAI_API_KEY) ? process.env.OPENAI_API_KEY : ""),
      baseUrl: provider === "gemini" ? DEFAULT_GEMINI_BASE_URL : DEFAULT_OPENAI_BASE_URL,
      model,
      apiFormat: DEFAULT_OPENAI_API_FORMAT,
      proxyUrl,
    };

    await writeEnvFile(config);
    printNextSteps(config);
  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error(error.message || String(error));
  process.exitCode = 1;
});
